import { Link } from 'react-router-dom';
import { ArrowLeft, Check, ChevronRight, Dumbbell, HeartPulse, UsersRound } from 'lucide-react';
import { BrandLogo } from '../../components/brand/BrandLogo';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { Card, CardContent } from '../../components/ui/Card';
import './marketing.css';

const colors = [['Gallery White', '#ffffff'], ['Studio Mist', '#f5f5f7'], ['Paper Frost', '#fafafc'], ['Ink', '#1d1d1f'], ['Slate', '#707070'], ['Action Blue', '#0071e3']];
export function DesignSystemPage() {
  return <main className="max-w-6xl mx-auto px-6 py-10 space-y-16"><header className="flex items-center justify-between gap-5"><BrandLogo /><Link to={import.meta.env.DEV ? '/design-preview' : '/landing'} className="flex items-center gap-2 text-sm text-indigo-600"><ArrowLeft size={16} />Voltar</Link></header><section className="max-w-3xl"><p className="text-sm text-slate-500 mb-5">FORMA GALLERY · SISTEMA VISUAL</p><h1 className="ds-display">Clareza em cada detalhe.</h1><p className="ds-body-lg text-slate-500 mt-6">Superfícies brancas, espaço para respirar e azul reservado às ações. Uma linguagem compartilhada por toda a plataforma.</p></section><section><h2 className="ds-h2 mb-6">Uma paleta essencial.</h2><div className="grid sm:grid-cols-3 gap-5">{colors.map(([name, color]) => <Card key={name}><div style={{ background: color }} className="h-28 rounded-t-[28px] border-b border-slate-100" /><CardContent><h3 className="font-medium">{name}</h3><code className="text-xs text-slate-500">{color}</code></CardContent></Card>)}</div></section><section><h2 className="ds-h2 mb-6">Tipo que orienta.</h2><Card><CardContent><p className="text-sm text-slate-500 mb-6">SF Pro quando disponível, com Helvetica Neue e Arial como alternativas locais. Pesos de 400 a 600.</p><div className="space-y-8"><p className="ds-display">Melhor forma.</p><p className="ds-h1">Seu método. Seu espaço.</p><p className="ds-body-lg">Texto de apoio em 17px, com entrelinha confortável.</p><p className="text-xs text-slate-500">Controles e legendas · 12px</p></div></CardContent></Card></section><section className="grid md:grid-cols-2 gap-5"><Card><CardContent><h2 className="ds-h2 mb-6">Ações e campos.</h2><div className="flex flex-wrap gap-3 mb-8"><Button>Continuar <ChevronRight size={16} /></Button><Button variant="outline">Explorar</Button><Button variant="ghost">Cancelar</Button></div><Input label="Seu nome" placeholder="Como você gosta de ser chamado?" id="example-name" /><p className="text-xs text-slate-500 mt-4">Controles arredondados. Foco visível. Rótulos claros.</p></CardContent></Card><Card><CardContent><h2 className="ds-h2 mb-6">Superfícies e ritmo.</h2><p className="ds-body text-slate-500">Cartões de 28px, sem sombras. Fundo cinza suave para separar seções. Espaçamento em múltiplos de 4px.</p><div className="flex gap-6 my-8">{[UsersRound, Dumbbell, HeartPulse, Check].map((Icon, i) => <Icon key={i} size={24} strokeWidth={1.5} />)}</div><p className="text-sm text-slate-500">Ícones discretos. Estados de sucesso, atenção e erro continuam semânticos.</p></CardContent></Card></section><footer className="text-xs text-slate-500 pb-8">Forma Training · Gallery · Referência visual do projeto</footer></main>;
}
